server:
  port: 9090


spring:
  datasource:
    username: root
    password: haominglu520
    url: jdbc:mysql://bj-cdb-msahut1q.sql.tencentcdb.com:60271/JavaWeb
#  datasource:
#    username: root
#    password: 123456
#    url: jdbc:mysql://localhost:3306/JavaWeb?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC


#    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: cn.edu.bjfu.javawebproject.pojo